export const UPDATE_VIDEOS_TO_BE_SHOWN = 'UPDATE_VIDEOS_TO_BE_SHOWN';
export const ADD_SEARCH_TERM = 'ADD_SEARCH_TERM';
export const UPDATE_REQUEST_PENDING = 'UPDATE_REQUEST_PENDING';
export const INCREASE_SAVED_VIDEO_COUNT = 'INCREASE_SAVED_VIDEO_COUNT';
export const DECREASE_SAVED_VIDEO_COUNT = 'DECREASE_SAVED_VIDEO_COUNT';
