export const dummyData = [
  {
    videoId: '1pfTxp25MA8',
    videoTitle: '[10분 테코톡] 🔮 히히의 OSI 7 Layer',
    channelId: 'UC-mOekGSesms0agFntnQang',
    channelTitle: '우아한Tech',
    publishedAt: '2020년 8월 25일',
    isSaved: true,
    isWatching: false,
  },
  {
    videoId: 'NkZ6r6z2pBg',
    videoTitle: '[10분 테코톡] 👨‍🏫안돌의 INDEX',
    channelId: 'UC-mOekGSesms0agFntnQang',
    channelTitle: '우아한Tech',
    publishedAt: '2019년 8월 26일',
    isSaved: true,
    isWatching: false,
  },
  {
    videoId: '9ZXIoh9PtwY',
    videoTitle: '[10분 테코톡] 🦋 레베카의 인덱스',
    channelId: 'UC-mOekGSesms0agFntnQang',
    channelTitle: '우아한Tech',
    publishedAt: '2020년 10월 14일',
    isSaved: true,
    isWatching: false,
  },
  {
    videoId: 'Fe3TVCEJhzo',
    videoTitle: '[10분 테코톡] 🐥엘리의 GC',
    channelId: 'UC-mOekGSesms0agFntnQang',
    channelTitle: '우아한Tech',
    publishedAt: '2020년 10월 20일',
    isSaved: true,
    isWatching: false,
  },
  {
    videoId: '6SvUZqbU37E',
    videoTitle: '[10분 테코톡] 🐳스티치의 빌드와 배포',
    channelId: 'UC-mOekGSesms0agFntnQang',
    channelTitle: '우아한Tech',
    publishedAt: '2020년 6월 19일',
    isSaved: true,
    isWatching: false,
  },
  {
    videoId: 'zGJzEBOELoU',
    videoTitle: '[10분 테코톡] 🙆‍♂️그래의 전략 패턴',
    channelId: 'UC-mOekGSesms0agFntnQang',
    channelTitle: '우아한Tech',
    publishedAt: '2020년 6월 8일',
    isSaved: true,
    isWatching: true,
  },
  {
    videoId: 'ikDVGYp5dhg',
    videoTitle: '[10분 테코톡] 👨‍🏫르윈의 TCP UDP',
    channelId: 'UC-mOekGSesms0agFntnQang',
    channelTitle: '우아한Tech',
    publishedAt: '2019년 10월 7일',
    isSaved: true,
    isWatching: true,
  },
  {
    videoId: 'NyhbNtOq0Bc',
    videoTitle: '[10분 테코톡] 👩‍🦰희봉의 웹서버 vs WAS',
    channelId: 'UC-mOekGSesms0agFntnQang',
    channelTitle: '우아한Tech',
    publishedAt: '2019년 8월 21일',
    isSaved: true,
    isWatching: true,
  },
  {
    videoId: 'DmZnOg5Ced8',
    videoTitle: '[10분 테코톡] 👩‍💻👨‍💻 쪼밀리와 오구의 Process vs Thread',
    channelId: 'UC-mOekGSesms0agFntnQang',
    channelTitle: '우아한Tech',
    publishedAt: '2020년 8월 4일',
    isSaved: true,
    isWatching: true,
  },
  {
    videoId: 'cmwmamOQmPc',
    videoTitle: '[10분 테코톡] 👨‍🎨규동의 Servlet & Spring',
    channelId: 'UC-mOekGSesms0agFntnQang',
    channelTitle: '우아한Tech',
    publishedAt: '2019년 11월 27일',
    isSaved: true,
    isWatching: true,
  },
];
