const mockData = [
  {
    url: 'https://i.ytimg.com/vi/ECfuKi5-Cfs/hq720.jpg?sqp=-oaymwEcCOgCEMoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDvmIcX-TgdcH2g_Bd4AUxw6hjmvQ',
    title: '[Playlist] 너무 좋은데 괜찮으시겠어요?',
    channelName: 'essential;',
    publishedDate: '2022년 3월 2일',
    saveButton: '⬇ 저장',
    id: 0,
  },
  {
    url: 'https://i.ytimg.com/vi/ECfuKi5-Cfs/hq720.jpg?sqp=-oaymwEcCOgCEMoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDvmIcX-TgdcH2g_Bd4AUxw6hjmvQ',
    title: '[Playlist] 너무 좋은데 괜찮으시겠어요?',
    channelName: 'essential;',
    publishedDate: '2022년 3월 2일',
    saveButton: '⬇ 저장',
    id: 1,
  },
  {
    url: 'https://i.ytimg.com/vi/ECfuKi5-Cfs/hq720.jpg?sqp=-oaymwEcCOgCEMoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDvmIcX-TgdcH2g_Bd4AUxw6hjmvQ',
    title: '[Playlist] 너무 좋은데 괜찮으시겠어요?',
    channelName: 'essential;',
    publishedDate: '2022년 3월 2일',
    saveButton: '⬇ 저장',
    id: 2,
  },
  {
    url: 'https://i.ytimg.com/vi/ECfuKi5-Cfs/hq720.jpg?sqp=-oaymwEcCOgCEMoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDvmIcX-TgdcH2g_Bd4AUxw6hjmvQ',
    title: '[Playlist] 너무 좋은데 괜찮으시겠어요?',
    channelName: 'essential;',
    publishedDate: '2022년 3월 2일',
    saveButton: '⬇ 저장',
    id: 3,
  },
  {
    url: 'https://i.ytimg.com/vi/ECfuKi5-Cfs/hq720.jpg?sqp=-oaymwEcCOgCEMoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDvmIcX-TgdcH2g_Bd4AUxw6hjmvQ',
    title: '[Playlist] 너무 좋은데 괜찮으시겠어요?',
    channelName: 'essential;',
    publishedDate: '2022년 3월 2일',
    saveButton: '⬇ 저장',
    id: 4,
  },
  {
    url: 'https://i.ytimg.com/vi/ECfuKi5-Cfs/hq720.jpg?sqp=-oaymwEcCOgCEMoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDvmIcX-TgdcH2g_Bd4AUxw6hjmvQ',
    title: '[Playlist] 너무 좋은데 괜찮으시겠어요?',
    channelName: 'essential;',
    publishedDate: '2022년 3월 2일',
    saveButton: '⬇ 저장',
    id: 5,
  },
  {
    url: 'https://i.ytimg.com/vi/ECfuKi5-Cfs/hq720.jpg?sqp=-oaymwEcCOgCEMoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDvmIcX-TgdcH2g_Bd4AUxw6hjmvQ',
    title: '[Playlist] 너무 좋은데 괜찮으시겠어요?',
    channelName: 'essential;',
    publishedDate: '2022년 3월 2일',
    saveButton: '⬇ 저장',
    id: 6,
  },
  {
    url: 'https://i.ytimg.com/vi/ECfuKi5-Cfs/hq720.jpg?sqp=-oaymwEcCOgCEMoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDvmIcX-TgdcH2g_Bd4AUxw6hjmvQ',
    title: '[Playlist] 너무 좋은데 괜찮으시겠어요?',
    channelName: 'essential;',
    publishedDate: '2022년 3월 2일',
    saveButton: '⬇ 저장',
    id: 7,
  },
  {
    url: 'https://i.ytimg.com/vi/ECfuKi5-Cfs/hq720.jpg?sqp=-oaymwEcCOgCEMoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDvmIcX-TgdcH2g_Bd4AUxw6hjmvQ',
    title: '[Playlist] 너무 좋은데 괜찮으시겠어요?',
    channelName: 'essential;',
    publishedDate: '2022년 3월 2일',
    saveButton: '⬇ 저장',
    id: 8,
  },
  {
    url: 'https://i.ytimg.com/vi/ECfuKi5-Cfs/hq720.jpg?sqp=-oaymwEcCOgCEMoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDvmIcX-TgdcH2g_Bd4AUxw6hjmvQ',
    title: '[Playlist] 너무 좋은데 괜찮으시겠어요?',
    channelName: 'essential;',
    publishedDate: '2022년 3월 2일',
    saveButton: '⬇ 저장',
    id: 9,
  },
];
