const MAX_SAVED_VIDEO_COUNT = 100;
const MAX_LATEST_KEYWORD_COUNT = 3;
const FETCH_VIDEO_COUNT = 10;

const NAN_CHARACTER = '-';

export {
  MAX_SAVED_VIDEO_COUNT,
  MAX_LATEST_KEYWORD_COUNT,
  FETCH_VIDEO_COUNT,
  NAN_CHARACTER,
};
