const ERROR_MESSAGE = {
  CANNOT_GET_YOUTUBE_VIDEO: '[404] 개발자에게 문의하세요',
  CANNOT_SEARCH_EMPTY: '공백은 검색할 수 없습니다.',
};

const MAX_VIDEO_COUNT = 10;
const MAX_VIDEO_LIST_LENGTH = 100;

export { ERROR_MESSAGE, MAX_VIDEO_COUNT, MAX_VIDEO_LIST_LENGTH };
