const MESSAGE = Object.freeze({
  KEYWORD_SUBMITTED: "KEYWORD_SUBMITTED",
  DATA_LOADED: "DATA_LOADED",
  HIDE_IF_VIDEO_IS_SAVED: "HIDE_IF_VIDEO_IS_SAVED",
  SAVE_VIDEO_BUTTON_CLICKED: "SAVE_VIDEO_BUTTON_CLICKED",
  SAVE_VIDEO: "SAVE_VIDEO",
  CANCEL_VIDEO_BUTTON_CLICKED: "CANCEL_VIDEO_BUTTON_CLICKED",
  SAVED_VIDEO_DELETED: "SAVED_VIDEO_DELETED",
  MOVE_TO_HISTORY_ICON_CLICKED: "MOVE_TO_HISTORY_ICON_CLICKED",
  MOVE_TO_WATCH_LATER_ICON_CLICKED: "MOVE_TO_WATCH_LATER_ICON_CLICKED",
});

export default MESSAGE;
